/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author Mert
 */
public class SiparisUygulamasi extends javax.swing.JFrame {

    Map<String, Integer> siparisler = new LinkedHashMap<>();

    /**
     * Creates new form SiparisUygulamasi
     */
    public SiparisUygulamasi() {
        initComponents();
    }

    public void siparisleriGoster() {
        String message = "";
        int tutar = 0;

        // map'in boş olup olmadığını gösterir
        if (siparisler.isEmpty()) {
            message = "Siparişiniz bulunmamaktadır.";
        } else {
            message += "Siparişler \n";

            for (Map.Entry<String, Integer> entry : siparisler.entrySet()) {
                message += entry.getKey() + "\n";
                tutar += entry.getValue();
            }
            message += "Toplam Tutar : " + tutar;
        }

        JOptionPane.showMessageDialog(this, message, "Siparişleriniz", HEIGHT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        iskenderCheckBox = new javax.swing.JCheckBox();
        beytiCheckBox = new javax.swing.JCheckBox();
        salataCheckBox = new javax.swing.JCheckBox();
        ayranCheckBox = new javax.swing.JCheckBox();
        siparisGosterButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sipariş Uygulaması");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Sipariş Uygulaması", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("MENÜ");

        iskenderCheckBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        iskenderCheckBox.setText("İskender - 15 TL");

        beytiCheckBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        beytiCheckBox.setText("Beyti - 12 TL");

        salataCheckBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        salataCheckBox.setText("Salata - 5 TL");

        ayranCheckBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ayranCheckBox.setText("Ayran - 2 TL");

        siparisGosterButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        siparisGosterButton.setText("Siparişleri Göster");
        siparisGosterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siparisGosterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ayranCheckBox)
                    .addComponent(salataCheckBox)
                    .addComponent(beytiCheckBox)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(iskenderCheckBox)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(37, 37, 37))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(siparisGosterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(iskenderCheckBox)
                .addGap(18, 18, 18)
                .addComponent(beytiCheckBox)
                .addGap(18, 18, 18)
                .addComponent(salataCheckBox)
                .addGap(18, 18, 18)
                .addComponent(ayranCheckBox)
                .addGap(37, 37, 37)
                .addComponent(siparisGosterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void siparisGosterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siparisGosterButtonActionPerformed
        // seçilenleri listeye ekle/listeden kaldır
        if (iskenderCheckBox.isSelected()) {
            siparisler.put("İskender", 15);
        } else {
            siparisler.remove("İskender");
        }

        if (beytiCheckBox.isSelected()) {
            siparisler.put("Beyti", 12);
        } else {
            siparisler.remove("Beyti");
        }

        if (salataCheckBox.isSelected()) {
            siparisler.put("Salata", 5);
        } else {
            siparisler.remove("Salata");
        }

        if (ayranCheckBox.isSelected()) {
            siparisler.put("Ayran", 2);
        } else {
            siparisler.remove("Ayran");
        }

        siparisleriGoster();
    }//GEN-LAST:event_siparisGosterButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SiparisUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SiparisUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SiparisUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SiparisUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SiparisUygulamasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ayranCheckBox;
    private javax.swing.JCheckBox beytiCheckBox;
    private javax.swing.JCheckBox iskenderCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox salataCheckBox;
    private javax.swing.JButton siparisGosterButton;
    // End of variables declaration//GEN-END:variables
}
